Fix default loading value
saramorillon/hooks pull request #1
Opened 2023-05-03 14:02 UTC by jbachayani

2023-05-03 17:41 UTC, saramorillon requested changes

2023-05-03 17:41 UTC, saramorillon commented on tests/unit/useCopy.test.ts
> +import { useCopy } from '../../src'
Pourquoi ces changements de path ? Je préfère qu'on garde le path vers le fichier lui même plutôt que vers son export dans l'index.

2023-05-03 18:05 UTC, jbachayani commented on tests/unit/useCopy.test.ts
> +import { useCopy } from '../../src'
C'était pour réduire au maximum la taille de l'import, mais je vais remettre comme avant ;)

2023-05-04 10:28 UTC, saramorillon approved these changes

2023-05-04 10:28 UTC, merged